  
version: 2.1

orbs:
  orb-orb: eddiewebb/orborb@dev:test
workflows:
  build-deploy:
    jobs:
      - validate:
          filters:
            branches:
              ignore: 
                - master
      - test:
          requires: 
            - validate
          filters:
            branches:
              only: 
                - staging
                - trying
      - publish:
          requires:
            - test
          filters:
            branches:
              only: staging




