
version: 2.1

parameters:
  orbnamespace: 
    type: string
    default: eddiewebb
  orbname: 
    type: string
    default: orborb

orbs:
  orborb: eddiewebb/orborb@0.1

workflows:
  build-deploy:
    jobs:
      - orborb/validate:
          name: validate
          filters:
            branches:
              ignore: 
                - master
      - orborb/test:
          name: Unit Tests
          orbnamespace: <<pipeline.parameters.orbnamespace>>
          orbname: <<pipeline.parameters.orbname>>
          ghi_name: eddiewebb
          requires: 
            - validate
          filters:
            branches:
              only: 
                - staging
                - trying
      - orborb/publish:
          orbname: <<pipeline.parameters.orbname>>
          orbnamespace: <<pipeline.parameters.orbnamespace>>
          ghi_name: eddiewebb
          requires:
            - Unit Tests
          filters:
            branches:
              only: staging




