  
version: 2.1

orbs:
  orb-orb: eddiewebb/orborb@dev:test

workflows:
  build-deploy:
    jobs:
      - orb-orb/validate:
          name: validate
          filters:
            branches:
              ignore: 
                - master
      - orb-orb/test:
          name: Unit Tests
          requires: 
            - validate
          filters:
            branches:
              only: 
                - staging
                - trying
      - orborb/publish:
          requires:
            - Unit Tests
          filters:
            branches:
              only: staging




