jobs:
  validate:
    docker:
      - image: cimg/base:2019.08
    working_directory: ~/repo
    steps:
      - checkout
      - install-circleci
      - pack-and-validate

  test:
    parameters:
      ghi_name:
        type: string
        default: ""
        description: GitHub username for bot adding comments
      orbname:
        type: string
        default: "myfirstorb"
        description: Change this to whatever name is correct for your orb.
      orbnamespace:
        type: string
        default: "eddiewebb"
        description: Change this to whatever name is correct for your orb.
    docker:
      - image: cimg/base:2019.08
    working_directory: ~/repo
    steps:
      - checkout
      - install-circleci
      - pack-and-validate
      - get-pr-info
      - publish-dev:
          orbname: <<parameters.orbname>>
          orbnamespace: <<parameters.orbnamespace>>
      - run-tests-bats:
          import: true
          orbname: <<parameters.orbname>>
          orbnamespace: <<parameters.orbnamespace>>
      - when:
          condition: <<parameters.ghi_name>> 
          steps:
            - add-pr-comment:
                ghi_name: <<parameters.ghi_name>> 

  publish:
    parameters:
      ghi_name:
        type: string
        default: ""
        description: GitHub username for bot adding comments
      orbname:
        type: string
        default: "myfirstorb"
        description: Change this to whatever name is correct for your orb.
      orbnamespace:
        type: string
        default: "eddiewebb"
        description: Change this to whatever name is correct for your orb.
    docker:
      - image: cimg/base:2019.08
    working_directory: ~/repo
    steps:
      - checkout
      - install-circleci   
      - get-pr-info  
      - promote-to-prod-semver:
          orbname: <<parameters.orbname>>
          orbnamespace: <<parameters.orbnamespace>>
      - when:
          condition: <<parameters.ghi_name>> 
          steps:
            - add-pr-comment:
                ghi_name: <<parameters.ghi_name>> 
