


parameters:
  orbname:
    type: string
    default: "myfirstorb"
    description: Change this to whatever name is correct for your orb.
  orbnamespace:
    type: string
    default: "eddiewebb"
    description: Change this to whatever name is correct for your orb.